config/routes.rb
Rails.application.routes.draw do

  devise_scope :usuario do
    get 'sign_out' => 'devise/sessions#destroy'
    get 'salir' => 'devise/sessions#destroy',
      as: :terminar_sesion
    post 'usuarios/iniciar_sesion', to: 'devise/sessions#create'
    get 'usuarios/iniciar_sesion', to: 'devise/sessions#new',
      as: :iniciar_sesion

    # El siguiente para superar mala generación del action en el formulario
    # cuando se autentica mal y esta montado no en / (genera 
    # /puntomontaje/puntomontaje/usuarios/sign_in )
    if (Rails.configuration.relative_url_root != '/') 
      ruta = File.join(Rails.configuration.relative_url_root, 
                       'usuarios/sign_in')
      post ruta, to: 'devise/sessions#create'
      get  ruta, to: 'devise/sessions#new'
    end
  end
  devise_for :usuarios, :skip => [:registrations], module: :devise
  as :usuario do
    get 'usuarios/edit' => 'devise/registrations#edit', 
      :as => 'editar_registro_usuario'    
    put 'usuarios/:id' => 'devise/registrations#update', 
      :as => 'registro_usuario'            
  end
  resources :usuarios, path_names: { new: 'nuevo', edit: 'edita' } 

  root to: 'msip/hogar#index'

  mount Msip::Engine, at: "/", as: 'msip'
  mount Sal7711Gen::Engine, at: "/", as: 'sal7711_gen'
end

app/models/ability.rb
class Ability  < Sal7711Gen::Ability

  # Autorizaciones con CanCanCan
  def initialize(usuario = nil)
    initialize_sal7711_gen(usuario)
  end

end

app/models/usuario.rb
require 'sal7711_gen/concerns/models/usuario'

class Usuario < ActiveRecord::Base
  include Sal7711Gen::Concerns::Models::Usuario
end

app/controllers/application_controller.rb
class ApplicationController < Msip::ApplicationController
  protect_from_forgery with: :exception

  # Sin definir control de acceso por ser utilidad
end

app/controllers/usuarios_controller.rb
require 'sal7711_gen/concerns/controllers/usuarios_controller'

class UsuariosController < Msip::ModelosController

  # Sin definir control de acceso por ser requerido por no autenticados
  
  include Sal7711Gen::Concerns::Controllers::UsuariosController    
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Sal7711Gen::ApplicationHelper
end

app/views/layouts/application.html.erb
<% content_for :title do %>
    <%= Msip.titulo %>
<% end %>

<% content_for :marca do %>
    <%= Msip.titulo %>
<% end %>

<% content_for :menu do %>
  <%= grupo_menus do %>
    <% if !current_usuario.nil? %>
      <%= opcion_menu "Buscar", sal7711_gen.buscar_path,
        desplegable: true %>
      <%= opcion_menu "Nuevo Artículo", sal7711_gen.new_articulo_path,
        desplegable: true %>
    <% end %>
  <% end %>
  <%= grupo_menus :pull => :right do %>
    <%= opcion_menu "Documentacion", File.join(
        Rails.configuration.relative_url_root, '/acercade') %>
    <% if !current_usuario.nil? %>
      <%= despliega_abajo "Administrar" do %>
        <%= opcion_menu "Clave y tema", main_app.editar_registro_usuario_path,
          desplegable: true %>
        <% if current_usuario.rol == Ability::ROLADMIN %>
          <%= opcion_menu "Usuarios", main_app.usuarios_path,
            desplegable: true %>
        <% end %>
        <% if current_usuario.rol == Ability::ROLADMIN %>
          <%= opcion_menu "Tablas Básicas", msip.tablasbasicas_path,
            desplegable: true %>
        <% end %>
      <% end %>
      <%= opcion_menu "Salir #{current_usuario.nusuario}", 
        main_app.terminar_sesion_path %>
    <% else %>
      <%= opcion_menu "Acerca de", File.join(
        Rails.configuration.relative_url_root, '/acercade') %>
      <%= opcion_menu "Iniciar Sesión", main_app.iniciar_sesion_path %> 
    <% end %>
  <% end %>
<% end %>

<% content_for :piedepagina do %>
  <p><span class='derechos'>Sistema de información de 
    <a href='https://gitlab.com/pasosdeJesus/sal7711'>código abierto</a> con 
    <a href="https://gitlab.com/pasosdeJesus/msip/-/blob/main/LICENCIA.md">licencia ISC</a>
    <br/>
    Desarrollado por <a id='pasosdeJesus' href="http://www.pasosdeJesus.org" target="_blank">Pasos de Jesús</a>. 2024. 
<% end %>

<%= render template: "layouts/sal7711_gen/application" %>